spring:
  application:
    name: game-platform
  datasource:
    url: jdbc:postgresql://localhost:5432/game_platform_db
    username: game_user
    password: game_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # This tells Kafka to convert our Java objects into JSON automatically
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8080
